### ISSUE TITLE
Prepare PX Toolbox for a POC integration into the PX for WP Plugin

### ISSUE THREAD

**Issue by schlessera** [ampproject/px-toolbox-php#21]
### Feature Description

An immediate priority is to set up the PX Toolbox with all that is needed to provide a proof-of-concept (POC) integration into the PX for WP Plugin.

This integration is meant to provide the CWV field data (if available) and lab data for any requested URL. To that end, we need to finalize the tooling integration far enough to retrieve the field data from the PageSpeed Insights API integration and the lab data from the Lighthouse data that is embedded within the former.

**Primar goals**
- [x] [Adapt tooling to include PSI API data outside of the embedded Lighthouse data](https://github.com/ampproject/px-toolbox-php/issues/17)
- [ ] [Add routing of the configuration to make the PSI API integration configurable from an external consumer](https://github.com/ampproject/px-toolbox-php/issues/18)

**Secondary goals**
- [ ] [Add logging to transport error state from individual tools to the final consumer](https://github.com/ampproject/px-toolbox-php/issues/19)
- [ ] [Add data formatting abstraction layer](https://github.com/ampproject/px-toolbox-php/issues/20)
